### ISSUE TITLE
it doesnot work on the latest vs code. 

### ISSUE THREAD

**Issue by fastzhong** [aslamanver/vsc-export#2]
I tried this extension today, but it doesnot work: Please wait, exporting...
 
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

MacOS: 10.15.7

**Comment by ghost-sage** [comment]
I downloaded and installed it.  Tried to run it and it does not and it does nothing:
﻿START

Exporting...

Successfully exported

END

In Visual Studio Code taskbar it shows that the export was successful, but it a false, because it created a brief file called vsclog.txt in the project folder and then the file disappears. 

Version: 1.53.2 (system setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by aslamanver** [comment]
We are working on fixes of the latest VS code versions.

**Comment by bkbonner** [comment]
I just tried it on the latest version of vs code and it seemed to work fine.  It generates vsc-extensions.txt

I am running:

Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
